// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXaEZZDq5iZVWRH97KnMOudSljWHPjk7Y',
    appId: '1:973890915528:web:6314b27932e86edd3f29fd',
    messagingSenderId: '973890915528',
    projectId: 'flutter-app1-4e604',
    authDomain: 'flutter-app1-4e604.firebaseapp.com',
    storageBucket: 'flutter-app1-4e604.appspot.com',
    measurementId: 'G-1R67CFP02B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2fEAnMulVcCuyGy6uKL26512wLC2atY0',
    appId: '1:973890915528:android:359922f526ff82823f29fd',
    messagingSenderId: '973890915528',
    projectId: 'flutter-app1-4e604',
    storageBucket: 'flutter-app1-4e604.appspot.com',
  );
}
